_target_: generator.diffusion_ts.gaussian_diffusion.Diffusion_TS
name: diffusion_ts

input_dim: 1 # or more depending on dataset
noise_dim: 256
cond_emb_dim: 64
shuffle: True
sparse_conditioning_loss_weight: 0.5 # sparse conditioning training sample weight for loss computation [0, 1]
freeze_cond_after_warmup: False # specify whether to freeze conditioning module parameters after warmup epoch

batch_size: 64
n_epochs: 1000
n_steps: 1000
base_lr: 1e-4
n_layer_enc: 4
n_layer_dec: 5
d_model: 128
sampling_timesteps: null
loss_type: l1 #l2
beta_schedule: cosine #linear
n_heads: 4
mlp_hidden_times: 4
eta: 0.0
attn_pd: 0.0
resid_pd: 0.0
kernel_size: null
padding_size: null
use_ff: true
reg_weight: null
gradient_accumulate_every: 2
ema_decay: 0.99
ema_update_interval: 10
lr_scheduler_params:
  factor: 0.5
  patience: 200
  min_lr: 1.0e-5
  threshold: 1.0e-1
  threshold_mode: rel
  verbose: false
warm_up_epochs: 200
use_ema_sampling: False
save_cycle: 1000
