datasets:
  pecanstreet:
    path: "home/fuest/EnData/data/pecanstreet/"
    columns: ["dataid", "local_15min", "car1", "car2", "grid", "solar", "solar2"]
  goinerdata:
    path: "home/fuest/EnData/data/pecanstreet/"
    columns: ["pv", "id"]
device: cpu
