defaults:
  - model: acgan
  - dataset: openpower
  - evaluator: default
  - _self_

device: 0 # 0, cpu
input_dim: 2 # or more depending on dataset
noise_dim: 256
cond_emb_dim: 64
shuffle: True
sparse_conditioning_loss_weight: 0.5 # sparse conditioning training sample weight for loss computation [0, 1]
freeze_cond_after_warmup: False # specify whether to freeze conditioning module parameters after warmup epochs
results_folder: ./checkpoints
