defaults:
  - model: acgan
  - dataset: default
  - evaluator: default
  - _self_

device: 0 # 0, cpu

job_name: ${model.name}_${dataset.name}_${dataset.user_group}
run_dir: outputs/${job_name}/${now:%Y-%m-%d_%H-%M-%S}

hydra:
  job_logging:
    version: 1
    formatters:
      simple:
        format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        level: INFO
    root:
      handlers: [console]
      level: INFO
  run:
    dir: ${run_dir}

wandb:
  project: endata
  entity: michael-fuest-technical-university-of-munich
