datasets:
  pecanstreetdata:
    path: "Users/michaelfuest/Research/DAI/EnData/data/pecanstreet/"
    columns: ["dataid", "local_15min", "car1", "car2", "grid", "solar", "solar2"]
  goinerdata:
    path: "Users/michaelfuest/Research/DAI/EnData/data/goiner/"
    columns: ["pv", "id"]
