datasets:
  pecanstreet:
    path: "./data/pecanstreet"
    data_columns: ["dataid",
     "local_15min",
     "car1",
     #"car2",
     "grid",
     "solar",
     #"solar2",
     ]
    metadata_columns: ["dataid",
      "building_type",
      #"pv",
      "solar",
      "car1",
      "city",
      "state",
      "total_square_footage",
      "house_construction_year"
    ]
  goinerdata:
    path: "./data/goinerdata/"
    columns: ["pv", "id"]
  openpower:
    path: "./data/openpower/"
    data_columns: ["utc_timestamp",
     "DE_KN_residential1_pv",
     "DE_KN_residential1_grid_import",
     "DE_KN_residential2_grid_import",
     "DE_KN_residential3_pv",
     "DE_KN_residential3_grid_import",
     "DE_KN_residential4_pv",
     "DE_KN_residential4_grid_import",
     "DE_KN_residential5_grid_import",
     "DE_KN_residential6_pv",
     "DE_KN_residential6_grid_import",
     ]
    user_flags: [True, False, True, True, False, True]
    ev_flags: [False, False, True, True, False, False]
