name: null
geography: null
normalize: True
threshold: 6 # int, clips values within +-threshold standard deviations when normalizing
include_generation: false
user_group: all
data_columns: []
metadata_columns: []

numeric_conditioning_bins: 5 # determines how many categories numerical vars are discretized into
conditioning_vars: {}
