name: default
normalize: True
scale: True
use_learned_normalizer: True
threshold: 6 # int, clips values within +-threshold standard deviations when normalizing
time_series_dims: 1
seq_len: 8

numeric_conditioning_bins: 5 # determines how many categories numerical vars are discretized into
conditioning_vars: {}
