name: default
normalize: True
threshold: 6 # int, clips values within +-threshold standard deviations when normalizing
input_dim: 1
seq_len: 8
user_group: all
shuffle: True

numeric_conditioning_bins: 5 # determines how many categories numerical vars are discretized into
conditioning_vars: {}
