name: openpower
geography: null
normalize: True
scale: True
threshold: 6 # int, bounds values within +-threshold stds
include_generation: False
input_dim: 1
user_group: all #pv_users, all
seq_len: 96
shuffle: True

path: "./data/openpower/csv"
data_columns: ["utc_timestamp",
  "DE_KN_residential1_pv",
  "DE_KN_residential1_grid_import",
  "DE_KN_residential2_grid_import",
  "DE_KN_residential3_pv",
  "DE_KN_residential3_grid_import",
  "DE_KN_residential4_pv",
  "DE_KN_residential4_grid_import",
  "DE_KN_residential5_grid_import",
  "DE_KN_residential6_pv",
  "DE_KN_residential6_grid_import",
  ]
user_flags: [True, False, True, True, False, True]
ev_flags: [False, False, True, True, False, False]

numeric_conditioning_bins: 5
conditioning_vars:
  month: 12
  weekday: 7
  year: 5
  ev: 2
  pv: 2
